### ISSUE TITLE
为什么下载这个没有lpl

### ISSUE THREAD

**Issue by TonyHeDonglin** [05lpl/SSAP-auto-calendar#1]
下载这个不是附送lpl嘛 我要可爱的乐乐 吸溜吸溜吸溜

**Comment by ETET114514** [comment]
同学我劝你善良

**Comment by 05lpl** [comment]
Hi!

Do you have more details around this error?

When did this start happening? After the most recent v2.1 release?
How many RMB do you donate?

**Comment by tongtongtot** [comment]
想要lpl服务就去买premium服务啊[doge] 只要$0.99一个月诶
